version: '3'
services:
  ## Replica set rs1
  mongo-rs1-01:
    container_name: mongo-rs1-01
    image: mongo
    volumes:
      - ./replicaSet.js:/replicaSet.js
    command: mongod --replSet rs1 --shardsvr --port 27017
    networks:
      - ${MONGO_NETWORK}
    depends_on:
      - mongo-rs1-02
      - mongo-rs1-03
  mongo-rs1-02:
    container_name: mongo-rs1-02
    image: mongo
    command: mongod --replSet rs1 --shardsvr --port 27017
    networks:
      - ${MONGO_NETWORK}
  mongo-rs1-03:
    container_name: mongo-rs1-03
    image: mongo
    command: mongod --replSet rs1 --shardsvr --port 27017
    networks:
      - ${MONGO_NETWORK}

networks:
  mongo-db-network:
    name: ${MONGO_NETWORK}
    external: true
