version: '3'
services:
  #Config servers
  config-server-1:
    container_name: config-server-1
    image: mongo
    volumes:
      - ./replicaSet.js:/replicaSet.js
    command: mongod --configsvr --replSet configServers --port 27017
    networks:
      - ${MONGO_NETWORK}
    depends_on:
      - config-server-2
      - config-server-3
  config-server-2:
    container_name: config-server-2
    image: mongo
    command: mongod --configsvr --replSet configServers --port 27017
    networks:
      - ${MONGO_NETWORK}
  config-server-3:
    container_name: config-server-3
    image: mongo
    command: mongod --configsvr --replSet configServers --port 27017
    networks:
      - ${MONGO_NETWORK}

networks:
  mongo-db-network:
    name: ${MONGO_NETWORK}
    external: true
