version: '3'
services:
  ## Replica set rs2
  mongo-rs2-01:
    image: mongo
    container_name: mongo-rs2-01
    volumes:
      - ./replicaSet.js:/replicaSet.js
      - ./setup.sh:/setup.sh
    command: mongod --replSet rs2 --shardsvr --port 27017
    networks:
      - ${MONGO_NETWORK}
    depends_on:
      - mongo-rs2-02
      - mongo-rs2-03
  mongo-rs2-02:
    image: mongo
    container_name: mongo-rs2-02
    command: mongod --replSet rs2 --shardsvr --port 27017
    networks:
      - ${MONGO_NETWORK}
  mongo-rs2-03:
    image: mongo
    container_name: mongo-rs2-03
    command: mongod --replSet rs2 --shardsvr --port 27017
    networks:
      - ${MONGO_NETWORK}

networks:
  mongo-db-network:
    name: ${MONGO_NETWORK}
    external: true
